# we will be using pydantic for schema validation
from pydantic import BaseModel, Field
from typing import List


class Source(BaseModel):
    """Schema for a source used by the agent"""

    # Field is used to provide metadata about the fields
    url: str = Field(..., description="The URL of the source document")


class AgentOutput(BaseModel):
    """Schema for the output of the agent with answer and sources"""

    answer: str = Field(..., description="The final answer generated by the agent")
    sources: List[Source] = Field(
        default_factory=list, description="List of sources used to generate the answer"
    )
